networks:
  annotation_network:
    name: annotation_network 

services:
  annotation_database:
    image: postgres:17
    container_name: annotation_database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: annotation_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - annotation_network

  annotation_backend:
    build: ../../api
    container_name: annotation_backend
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      FLASK_ENV: development
    ports:
      - "5001:5000"
    volumes:
      - ../../api:/app
    networks:
      - annotation_network
    depends_on:
      - annotation_database

  annotation_pipeline:
    build: ../../pipeline
    container_name: annotation_pipeline
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      FLASK_ENV: development
      PYTHONUNBUFFERED: 1
      FLASK_RUN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ../../pipeline:/app
    networks:
      - annotation_network

  annotation_difference_calc:
    build: ../../difference-calc
    container_name: annotation_difference_calc
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_RUN_PORT: 8443
    ports:
      - "8443:8443"
    volumes:
      - ../../difference-calc:/app
    networks:
      - annotation_network

  annotation_frontend:
    build: ../../frontend
    container_name: annotation_frontend
    stdin_open: true
    ports:
      - "5173:5173"
    volumes:
      - '../../frontend:/app'
      - 'node_modules:/app/node_modules'
    depends_on:
      - annotation_backend
    networks:
      - annotation_network


  nginx:
    image: nginx:latest
    container_name: annotation_nginx
    ports:
      - "80:80"
    depends_on:
      - annotation_frontend
      - annotation_backend
      - annotation_difference_calc
      - annotation_pipeline
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - annotation_network

volumes:
  data:
    name: annotation_data
    external: true # Cloned volume is marked as external
  node_modules:
    name: node_modules
