services:
  db:
    image: postgres:17
    container_name: annotation_database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: annotation_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  flask-api:
    build: ../../api
    container_name: annotation_backend
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      FLASK_ENV: development
    ports:
      - "5001:5000"
    volumes:
      - ../../api:/app
    depends_on:
      - db

  flask-pipeline:
    build: ../../pipeline
    container_name: annotation_pipeline
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_RUN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ../../pipeline:/app

  flask-difference-calc:
    build: ../../difference-calc
    container_name: annotation_difference_calc
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      FLASK_ENV: development
      FLASK_RUN_PORT: 8443
    ports:
      - "8443:8443"
    volumes:
      - ../../difference-calc:/app

  react:
    build: ../../frontend
    container_name: annotation_frontend
    stdin_open: true
    ports: 
      - "5173:5173"
    volumes:
      - '../../frontend:/app'
      - '/app/node_modules'
    depends_on:
      - flask-api

  nginx:
    image: nginx:latest
    container_name: annotation_nginx
    ports:
      - "80:80"
    depends_on:
      - react
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  data:
    name: annotation_data
